package com.learn.collections;

import java.util.ArrayList;
import java.util.HashMap;

class SalesPerson {
    private int id;
    private String name;

    public SalesPerson(int id, String name) {
        this.id = id;
        this.name = name;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }
}

class Product {
    private int productId;
    private String name;
    private double price;

    public Product(int productId, String name, double price) {
        this.productId = productId;
        this.name = name;
        this.price = price;
    }

    public int getProductId() {
        return productId;
    }

    public String getName() {
        return name;
    }

    public double getPrice() {
        return price;
    }
}

class Sale{
    private SalesPerson salesPerson;
    private Product product;
    private int quantity;

    public Sale(SalesPerson salesPerson, Product product, int quantity) {
        this.salesPerson = salesPerson;
        this.product = product;
        this.quantity = quantity;
    }

    public SalesPerson getSalesPerson() {
        return salesPerson;
    }

    public Product getProduct() {
        return product;
    }

    public int getQuantity() {
        return quantity;
    }

    public double getRevenue(){
        return product.getPrice() * quantity;
    }
}

class Company{
    ArrayList<SalesPerson> salesPeople;
    ArrayList<Sale> sales;

    HashMap<String, Product > products;

    public Company(ArrayList<SalesPerson> salesPeople, HashMap<String, Product> products, ArrayList<Sale> sales) {
        this.salesPeople = salesPeople;
        this.products = products;
        this.sales = sales;
    }

    public void addSalesPerson(SalesPerson salesPerson){
        salesPeople.add(salesPerson);
    }

    public void addProduct(Product product){
        products.put(product.getName(), product);
    }
    public void recordSale(Sale sale){
        sales.add(sale);
    }

    // to get the total revenue generated by the company,
    public double getTotalRevenue(){
        double total = 0;
        for (var sale : sales){
            total += sale.getRevenue();
        }
        return total;
    }

    public void getBestEmployee(){
        SalesPerson bestSlave = null;
        double maxrevenue = 0;
        for (var slave : salesPeople){
           double moneyGenerated =  getSalespersonRevenue(slave);
                if (moneyGenerated > maxrevenue){
                    bestSlave = slave;
                    maxrevenue = moneyGenerated;
                }
            }
        System.out.println("Best Slave of the year goes to " + bestSlave.getName());
        }


    public double getSalespersonRevenue(SalesPerson salesPerson){
        double salesPersonTotal = 0;
        for (var sale : sales){
            if (sale.getSalesPerson().getName().equals(salesPerson.getName())){
                salesPersonTotal += sale.getRevenue();
            }
        }
        return salesPersonTotal;
    }

    public double getProductRevenue(Product product){
        double productTotal = 0;
        for (var sale : sales){
            if (sale.getProduct().getName().equals(product.getName())){
                productTotal += sale.getRevenue();
            }
        }
        return productTotal;
    }
}

public class SalesCal {

    public static void main(String[] args) {

        // Create a list of salespeople
        ArrayList<SalesPerson> salesPeople = new ArrayList<>();
        SalesPerson john = new SalesPerson(1, "John Smith");
        SalesPerson jane = new SalesPerson(2, "Jane Doe");
        salesPeople.add(john);
        salesPeople.add(jane);

        // Create a map of products
        HashMap<String, Product> products = new HashMap<>();
        Product laptop = new Product(1, "Laptop", 1000);
        Product phone = new Product(2, "Phone", 500);
        products.put(laptop.getName(), laptop);
        products.put(phone.getName(), phone);

        // Create a list of sales
        ArrayList<Sale> sales = new ArrayList<>();
        Sale sale1 = new Sale(john, laptop, 2);
        Sale sale2 = new Sale(jane, phone, 3);
        Sale sale3 = new Sale(john, phone, 1);
        sales.add(sale1);
        sales.add(sale2);
        sales.add(sale3);

        // Create a company object and add the salespeople, products, and sales
        Company company = new Company(salesPeople, products, sales);
        company.getBestEmployee();

        // Print the total revenue generated by the company
        System.out.println("Total revenue generated by the company: $" + company.getTotalRevenue());

        System.out.println("Revenue generated by John Smith: $" + company.getSalespersonRevenue(john));
        System.out.println("Revenue generated by Jane Doe: $" + company.getSalespersonRevenue(jane));


        // Print the revenue generated by phones
        System.out.println("Revenue generated by phones: $" + company.getProductRevenue(phone));



    }
}